---
- name: daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart factorio units
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    enabled: true
  loop: "{{ factorio_units | default([]) }}"